security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      custom_authenticator:
        - App\Security\GoogleAuthenticator

      logout:
        path: app_logout
        target: app_homepage

      # Configuration d'expiration de session via remember_me
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 86400 # 24 heures en secondes
        signature_properties: ["password", "updatedAt"]
        secure: true
        samesite: "strict"

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/article/new, roles: ROLE_REDACTOR }
    - { path: ^/article/\d+/edit, roles: ROLE_REDACTOR }
    - { path: ^/connect/google, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/account, roles: ROLE_USER }

  role_hierarchy:
    ROLE_ADMIN: ROLE_REDACTOR
    ROLE_REDACTOR: ROLE_USER
